### ISSUE TITLE
Screenshot as banner

### ISSUE THREAD

**Issue by haesleinhuepf** [mpicbg-csbd/napari-kics#3]
Hi @a-ludi and @adibrov ,

congrats to this fantastic napari plugin! I'm looking forward to its public release. Just one minor suggestion: 

In the readme, right after the first sentence describing what the plugin does, put a screenshot so that people can see it visually without reading text. E.g. this screenshot from the video would be cool:

![image](https://user-images.githubusercontent.com/12660498/166313105-880e8d17-e9ee-4b81-b1e1-dd0c021ee878.png)

Cheers,
Robert

**Comment by a-ludi** [comment]
Fixed in commit 559f8d1ab81d67929dc528d105a178e24f98adcc.
